
/*
 ***************************************************************
 * This file is autogenerated. Modifications to its contents   *
 * will not be persistent. Modify the template source instead. *
 ***************************************************************
 */
/*
 * syscall_numbers.h
 *
 *  Created on: Mar 18, 2015
 *      Author: Kevin
 */

#ifndef SYSCALL_NUMBERS_H_
#define SYSCALL_NUMBERS_H_

#define SYSCALL_EXIT          	(0)
#define SYSCALL_YIELD         	(1)
#define SYSCALL_SLEEP         	(2)
#define SYSCALL_SPAWN         	(3)
#define SYSCALL_FORK          	(4)
#define SYSCALL_RESET         	(5)
#define SYSCALL_WAIT          	(6)
#define SYSCALL_KILL          	(7)
#define SYSCALL_GET_TID       	(8)
#define SYSCALL_LOCK          	(9)
#define SYSCALL_UNLOCK        	(10)

#endif /* SYSCALL_NUMBERS_H_ */
